- lib/swagger-explorer.ts
Fixed an issue having multiple in path parameters. Only the first encountered was being replaced.
> Parse all in path parameters

- lib/interfaces/swagger-base-config.interface.ts
- lib/swagger-module.ts
Set the swagger version to 2.0 as described on [the doc](https://swagger.io/docs/specification/2-0/basic-structure/)
I assume the format is in swagger 2.0 due to how the `body` parameters are reported which I think isn't valid for swagger 3.0.
> Set swagger version

- lib/document-builder.ts
- lib/explorers/api-parameters.explorer.ts
- lib/explorers/api-response.explorer.ts
- lib/fixtures/document.base.ts
- lib/swagger-explorer.ts
According to OpenAPI Specification:
1. basePath must start with "/".
2. response should not contain additional properties (isArray).
3. required fields should be an array in Schema Object (resolves #24).
> Fix OpenAPI Specification inconsistencies

- lib/explorers/api-parameters.explorer.ts
@kamilmysliwiec it is a simple change and works perfectly. Is there any reason for not including it to the map?
> Add support for @Headers('property') parameter decorator.

- lib/decorators/api-model-property.decorator.ts
- lib/explorers/api-parameters.explorer.ts
~~**DISCLAIMER** Looks like a duplicate of https://github.com/nestjs/swagger/pull/44~~
**TLDR;** This PR adds the `enum` property to the `@ApiModelProperty()` decorator
_This PR might also solve https://github.com/nestjs/swagger/issues/19_
---
This PR slightly updates the `@ApiModelProperty()` options by adding the `enum?: string[] | number[] | (string|number)[]`.
Here is a pretty self explanatory example:
```js
export class SampleDto {
@ApiModelProperty({
enum: ["String1", "String2"]
})
prop1: string;
@ApiModelProperty({
enum: ["String1", 2]
})
prop2: string;
@ApiModelProperty({
enum: [1, 2]
})
prop3: number;
}
```
> Add JSON Schema Object properties support to the ApiModelProperty decorator

- lib/decorators/api-implicit-body.decorator.ts
- lib/explorers/api-parameters.explorer.ts
Add `isArray` support for ApiImplicitBody decorator
```
class Pet {
@ApiModelProperty()
readonly name: string;
}
@Controller("pets")
class PetsController {
@ApiImplicitBody({ type: Pet, isArray: true, name: "Object" })
addMany(@Body() pets: Pet[]) {
}
}
```
> Add `isArray` support for ApiImplicitBody decorator

- lib/decorators/api-implicit-query.decorator.ts
Conforms to swagger 2.0 spec for array definitions - should help clean up docs and make testing easier through the swagger ui:
> Add support for arrays in ApiImplicitQuery

- lib/swagger-explorer.ts
- package.json
Right now the [Express docs][route-parameters] contain paths which are not properly handled by this swagger extension, for example:
>      Route path: /plantae/:genus.:species
>      Request URL: http://localhost:3000/plantae/Prunus.persica
>      req.params: { "genus": "Prunus", "species": "persica" }
generates an OpenAPI doc for the path `/plantae/{genus.:species}`. The Express route still works but tools like `swagger-ui` have problems.
The underlying Express code [indicates that this responsibility was packaged into its own library][document-import], the package [path-to-regexp](https://www.npmjs.com/package/path-to-regexp), which already does all of the "remove the trailing regexp" difficult stuff for you. It seems like the proper way for this project to proceed is, rather than …
> Update validateRoutePath to use Express's path-to-regexp lib

- lib/explorers/api-parameters.explorer.ts
There are no tests in this repo, one is provided in the associated ticket.
There is no need to update any doc.
```
[X] Bugfix
[ ] Feature
```
Issue Number: #118 
Use `allOf` to mix the model `$ref` and any other metadata set by the `ApiModelProperty` decorator, except `type`, `isArray` (along with `collectionFormat`) and `required` which seem to have special treatment throughout this repo:
```
{
description?: string;
required?: boolean; // REMOVED FROM allOf
type?: any; // REMOVED FROM allOf
isArray?: …
```
> Fix #118 - Add missing metadata on `$ref` types using `allOf`

- lib/decorators/api-response.decorator.ts
- The number of "shortcut" ApiResponses matches with the number of "shortcut" HttpExceptions.
```
[ ] Bugfix
[x] Feature
```
Various "shortcut" to `@ApiResponse` have been added in according to `HttpStatus`. The number of the added decorators matches with the number of **shortcut** `HttpException`.
```
[ ] Yes
[x] No
```
> Added various ApiResponses decorators based on HttpStatus

- lib/swagger-module.ts
- lib/swagger-scanner.ts
```
[ ] Bugfix
[x] Feature
```
As #129 mentioned, there currently is no way to make this work.
Issue Number: #129 
`SwaggerModule` now supports multiple spec files to be served on different SwaggerUI Routes.
```javascript
const swaggerDoc = SwaggerModule.createDocument(app, swaggerOptions, [SecondaryModule]);
const swaggerDoc2 = SwaggerModule.createDocument(app, swaggerOptions, [ThirdModule]);
SwaggerModule.setup('/api/docs', app, swaggerDoc);
SwaggerModule.setup('/api/docs2', app, swaggerDoc2);
``` …
> Support multiple spec files

- lib/decorators/api-response.decorator.ts
Added missing `ApiResponse` wrappers for commonly used http statuses: 
- `202 ACCEPTED` - `@ApiAcceptedResponse()`
- `204 NO CONTENT` - `@ApiNoContentResponse()`
- `302 MOVED PERMANENTLY` - `@ApiMovedPermanentlyResponse()`
- `401 UNAUTHORIZED` - `@ApiUnauthorizedResponse()`
- `429 TOO MANY REQUESTS` - `@ApiTooManyRequestsResponse()`
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> Add ApiResponse wrappers for missing status codes

- lib/explorers/api-parameters.explorer.ts
Fix circular dependency throws maximum call stack size exceeded
```
[x] Bugfix
[ ] Feature
```
Issue Number: #136 #175 
```
[ ] Yes
[x] No
```
> Fix circular dependency throws error

- lib/swagger-module.ts
- package.json
```
[x] Bugfix
[ ] Feature
```
swagger-ui-express loads using JS import, so it's impossible to use this package without express installation. 
Issue Number: #215 
swagger-ui-express for now loads dynamically, so there is no need in express package when FastifyAdapter is used. Also I remove swagger-ui-express & fastify-swagger from dependencies & devDependencies.
```
[x] Yes
[] No
```
For express usage it's needed to install swagger-ui-express package manually. Old behavior can be achieved by reverting …
> Dynamic swagger-ui-express loading

- lib/decorators/api-response.decorator.ts
Move headers to ResponseMetadata interface to allow it being used from the helper decorators as well.
```
[ ] Bugfix
[x] Feature
```
ResponseMetadata interface does not contain headers property.
ResponseMetadata interface includes headers property.
```
[ ] Yes
[x] No
```
> feature(api-response): Headers to ResponseMetadata

- lib/swagger-module.ts
```
[x] Bugfix
[ ] Feature
```
`SwaggerScanner` is instantiated once, and thus, always uses the same instance of `SwaggerExplorer`, which leads to compounding `modelsDefinitions` at each call of `createDocument`. Thus, only the first swagger document created has a valid list of "Models". The other ones have their models and all the ones previously scanned.
Instantiate a new Scanner for each Document created, so we never re-use data from the previous documents. 
```
[ ] Yes
[x] No
```
> fix: create a Scanner when calling createDocument

- lib/document-builder.ts
- lib/fixtures/document.base.ts
Addresses #190 
Tags are "inherited" from a specification to an other, as "documentBase" (`this.document` in `DocumentBuilder`) is never renewed (and tags are always appended in the existing array).
Issue Number: #190 
The "documentBase" is now recreated anytime `DocumentBuilder` is instantiated.
> fix(document-builder): always use a new base

- lib/interfaces/swagger-document-options.interface.ts
- lib/swagger-module.ts
- lib/swagger-scanner.ts
Hi there!
_**This PR is a first proposal**. If it can be considered as an enhancement, I'd be glad to leave it "as is".
I noticed that the [Multiple Specifications](https://docs.nestjs.com/recipes/swagger#multiple-specifications) was not loading the controllers of the "sub modules" of any module passed in `include`.
Meaning that in the given example, if `CatsModule` imports `CatToysModule` which has its own controller `CatToysController`, its route won't be scanned and loaded in the OpenAPI configuration.
The `swagger-scanner` is exploring all the `relatedModules` of the `include`d modules to load their routes too, if the option `deepScanRoutes: true` is passed along …
> feat(scanner): explore included modules for routes

- lib/swagger-explorer.ts
```
[x] Bugfix
[ ] Feature
```
Issue Number: https://github.com/shekohex/nest-router/issues/3
The Issue was previously fixed at #104 , but recently some developers are reporting issue with `swagger-ui` as described here https://github.com/shekohex/nest-router/issues/3#issuecomment-476000073. the issue is simply solved by just rerun the route validation function on the route if it has a `modulePath`.
This issue is now fixed and now `@nestjs/swagger` should provide the correct ui route
```
[ ] Yes
[x] No …
```
> [hotfix]: Fix Another Issue with Nest Router Package and Swagger Integration.

- lib/decorators/api-model-property.decorator.ts
(Explanation: Checking through the rest of the repo I am not seeing any tests for `maximum` or `exclusiveMaximum`, say, nor any documentation other than that they exist in the first place?)
```
[ ] Bugfix
[x] Feature
```
Currently the system type-errors when you try to specify that a field could be `null` because the `nullable` flag does not exist as an allowed piece of `ApiModelProperty` data.
This adds it. If I am understanding the repository's function right, it then gets copied into swagger docs …
> feature: add OpenAPI's nullable flag to APIModelProperty

- lib/explorers/api-parameters.explorer.ts
```
[x] Bugfix
[ ] Feature
```
When the request content type is 'multipart/form-data' swagger does not properly generate property fields on a request according to a passed DTO type.
If an action is decorated with '@ApiConsumes('multipart/form-data')', it now will check for it and change it's parsing flow from 'body' type to 'formData'.
```
[ ] Yes
[x] No
```
> Fix for param type in docs for 'multipart/form-data' requests

- lib/swagger-explorer.ts
- test/explorer/swagger-explorer.spec.ts
```
[x] Bugfix
[ ] Feature
```
Operation ID == method name
Issue Number: #482 
Operation ID == ClassName_MethodName
```
[ ] Yes
[ ] No
```
> fix(): use unique operation id for each endpoint (class_method)

- lib/plugin/visitors/model-class.visitor.ts
- test/plugin/fixtures/create-cat-alt2.dto.ts
- test/plugin/model-class-visitor.spec.ts
Solves the error "Error Cannot read property 'kind' of undefined"
Fixes #513
- I don't think that it is necessary
```
[X] Bugfix
[ ] Feature
```
Issue Number: 513
Error on nest build when using plugin
Build without error.
```
[ ] Yes
[X] No
```
> fix(core): error 'kind' of undefined

- lib/decorators/api-security.decorator.ts
Fixes #522
```
[x] Bugfix
[ ] Feature
```
Issue Number: #522 
Fixed
```
[ ] Yes
[x] No
```
> fix(): TypeError when using @ApiSecurity on controller method

- test/plugin/controller-class-visitor.spec.ts
- test/plugin/model-class-visitor.spec.ts
This allows tests to run normally on Windows.
- [N/A] Docs have been added / updated (for bug fixes / features)
```
[ ] Bugfix
[ ] Feature
[x] CI related changes
```
The new line of tests was left as the default. However, on Windows, TypeScript generates files with Windows line endings, making the test expectations not match.
New line is explicitly set to linux line endings, so that regardless of what platform the tests are executed on, the tests will pass.
```
[ ] Yes
[x] No
```
> test(platform): Explicitly added a new line type to tests

- e2e/api-spec.json
- lib/services/schema-object-factory.ts
- test/services/fixtures/create-user.dto.ts
- test/services/schema-object-factory.spec.ts
Fixes #549
```
[x] Bugfix
[ ] Feature
```
Issue Number: #549
Behavious is described in ticket
New behaviour is describe in ticket and also in the test suite.
```
[x] Yes
[ ] No
```
If anyone was relying on the exact generated spec for nested properties, this would break it for them.
As the generated spec was not a valid OAS 3.0 specification, I think it is okay to break the existing behaviour.
> fix(): nested schema with additional properties causes invalid spec

- e2e/api-spec.json
- e2e/fastify.e2e-spec.ts
- e2e/validate-schema.e2e-spec.ts
- lib/decorators/api-cookie.decorator.ts
- lib/document-builder.ts
```
[ ] Bugfix
[x] Feature
```
Issue Number: #649 
```
// main.ts
const options = new DocumentBuilder()
.setTitle('Cats example')
.setDescription('The cats API description')
.setVersion('1.0')
.addTag('cats')
.addCookieAuth() // <- adds cookie authentication
.build();
// cats.controller.ts
@ApiCookieAuth() // <- adds cookie authentication
@Controller('cats')
export class CatsController {}
```
```
[ ] Yes
[x] No
```
> OpenAPI 3 Cookie Authentication Support

- e2e/api-spec.json
- e2e/src/cats/cats.controller.ts
- lib/decorators/api-extension.decorator.ts
```
[x] Bugfix
[ ] Feature
```
The current `@ApiExtension` produces a wrong json output when the extension is a string.
The following extension `@ApiExtension('x-key', 'VALUE');` produces:
```json
{
"x-key": { "0": "V", "1": "A", "2": "L", "3": "U", "4": "E" }
}
```
```json
{
"x-key": "VALUE"
}
```
```
[ ] Yes
[x] No
```
> fix(api-extension): add support for string extensions

- lib/services/schema-object-factory.ts
- test/services/fixtures/create-user.dto.ts
- test/services/schema-object-factory.spec.ts
- [ x ] The commit message follows our guidelines: https://github.com/nestjs/nest/blob/master/CONTRIBUTING.md
- [ x ] Tests for the changes have been added (for bug fixes / features)
```
[ x ] Bugfix
[ ] Feature
```
Using the following options: 
```
@ApiProperty({ type: 'integer', isArray: true })
someProp: number[];
```
Produces the following swagger parameter definition, ignoring the isArray flag:
```
"someProp": {
"type": "integer",
},
```
Now, when the type option is a string, the …
> fix(): process isarray for string based property type

- lib/services/schema-object-factory.ts
- test/services/schema-object-factory.spec.ts
fix #808
```
[x] Bugfix
[ ] Feature
```
Issue Number: #808 
`@ApiProperty({ enum: EnumType, enumName: 'EnumType', isArray: true })` should produce the correct schema 
```
{
"type": "array",
"items": {
"$ref$": "#/components/schemas/EnumType"
}
}
```
```
[ ] Yes
[x] No
```
> fix(lib): fix enum array on model properties

- lib/plugin/visitors/model-class.visitor.ts
- test/plugin/fixtures/nullable.dto.ts
- test/plugin/model-class-visitor.spec.ts
`nullableValOpt?: string | null;` now results in `type`=`string`, `nullable`=`true`
before this change, the type was object
this fixes #912
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> feat(@nestjs/swagger): CLI plugin now supports nullable

- lib/decorators/api-response.decorator.ts
```
[ ] Bugfix
[x] Feature
```
OpenAPI's schema have optional parameter `$ref`, but `ApiResponse` decorator does not accept `schema.$ref`.
`ApiResponse` accepts `schema.$ref`. This change is valuable when we want to use a shema that is defined in external spec file. For Example, now we can write `@ApiResponse({schema: {$ref: '../path/to/yaml#components/schemas/SomeSchema}})`.
```
[ ] Yes
[x] No
```
> feat(api-response): support $ref

- lib/plugin/visitors/model-class.visitor.ts
- test/plugin/fixtures/changed-class.dto.ts
- test/plugin/model-class-visitor.spec.ts
```
[x] Bugfix
[ ] Feature
```
When using swagger plugin with tsc/ttsc in watch mode, removing property from DTO does not lead to its removal from metadata until tsc/ttsc is restarted.
This behavior can be reproduced in https://github.com/artemsmirnov/nestjs-swagger-bug-demo by starting it with
`node index.js` and then removing `foo` or `test` property from `src/example.dto.ts`.
Metadata is updated according to changes in source file.
```
[ ] Yes
[x] No
```
> fix(plugin): update metadata correctly when using plugin in watch mode

- .gitignore
- lib/plugin/compiler-plugin.ts
- lib/plugin/merge-options.ts
- lib/plugin/utils/ast-utils.ts
- lib/plugin/visitors/controller-class.visitor.ts
- lib/plugin/visitors/model-class.visitor.ts
- test/plugin/controller-class-visitor.spec.ts
- test/plugin/fixtures/app.controller.ts
- test/plugin/fixtures/create-cat-alt.dto.ts
- test/plugin/fixtures/create-cat-alt2.dto.ts
- test/plugin/fixtures/create-cat.dto.ts
- test/plugin/fixtures/es5-class.dto.ts
- test/plugin/model-class-visitor.spec.ts
test added.
no docs in this project yet.
```
[ ] Bugfix
[x] Feature
```
When enable the plugin by modified nest-cli.json , there is no default `description` and `example` in `ApiProperty` and `ApiOperation`
Auto generate `description` and (`example` or `examples`) from comment, just like this:
```
export abstract class Audit {
/** test on createdAt */
@CreateDateColumn()
createdAt;
// test on updatedAt1
// test on updatedAt2
@UpdateDateColumn()
updatedAt;
/**
* test
* version 
* @example '0.0.1'
* …
```
> auto generate description from comments

- lib/type-helpers/intersection-type.helper.ts
- package-lock.json
- package.json
```
[x] Bugfix
[ ] Feature
```
Default property value are not inherit. 
[https://github.com/nestjs/mapped-types/issues/199](https://github.com/nestjs/mapped-types/issues/199)
[https://github.com/nestjs/swagger/issues/875](https://github.com/nestjs/swagger/issues/875)
Issue Number: #875
Default property value are passed. To work with Swagger OpenAPI is neccessary to put it in @ApiProperty() decoratora as default value. 
```ts
@ApiProperty({ default: "queryPhrase 2" })
queryPhrase: string = "queryPhrase …
```
> fix: IntersectionType doesn't inherit default values #875

- lib/decorators/api-response.decorator.ts
```
[ ] Bugfix
[x] Feature
```
Commit 759241607 states that it adds a wrapper for 302 MOVED PERMANENTLY. It does add [MOVED PERMANENTLY](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/301), but that is a [301 response](https://github.com/nestjs/nest/blob/v7.4.4/packages/common/enums/http-status.enum.ts#L13).
To produce API documentation that reports that an endpoint could return a 302 FOUND, one must use `ApiResponse()`:
```js
@ApiResponse({
status: HttpStatus.FOUND, …
```
> feat: Add ApiResponse wrapper for 302 FOUND

- lib/interfaces/swagger-document-options.interface.ts
- lib/plugin/visitors/model-class.visitor.ts
- lib/swagger-explorer.ts
- lib/swagger-scanner.ts
- test/explorer/swagger-explorer.spec.ts
Make the behavior change for operation names that was introduced in https://github.com/nestjs/swagger/pull/487 configurable, and allow users whose client libraries have broken because of this (see https://github.com/nestjs/swagger/issues/482) to configure this behavior.
```
[ ] Bugfix
[x] Feature
```
Since #487 was merged, operation IDs generated by NestJS changed from e.g.
```
addUser
```
to
```
UserController_addUser
```
... this is causing users of generated client libraries (e.g. Angular) to have …
> feat(): add use method name for operations option

- lib/services/schema-object-factory.ts
- test/services/fixtures/create-user.dto.ts
- test/services/schema-object-factory.spec.ts
```
[x] Bugfix
[ ] Feature
```
When using the `description` and `nullable` properties on a nested object, they are not properly added to the schema. So they are not visible in the Swagger UI and `nullable` is not interpreted by the typescript-axios lang of openapi-generator.
Extract of the generated Schema:
```
{
"NestedObjectDto": {
"type": "object",
"properties": {
"foo": {
"allOf": [{
"$ref": "#/components/schemas/NestedPropertyDto"
}, {
"description": "Foo",
"nullable": true
}]
}
},
"required": …
```
> fix(): nested schema additional properties take place next to allof

- lib/interfaces/swagger-custom-options.interface.ts
We had a discussion here about this change: https://github.com/nestjs/docs.nestjs.com/pull/1645#discussion_r565926754
```
[ ] Bugfix
[ ] Feature
```
`swaggerOptions` accepts any type of parameters like boolean or string.
`swaggerOptions` should accept only object type.
```
[ ] Yes
[x] No
```
We had a discussion [here ]( https://github.com/nestjs/docs.nestjs.com/pull/1645#discussion_r565926754)about this change.
> refactor(setup): change swaggerOptions type

- e2e/api-spec.json
- e2e/fastify.e2e-spec.ts
- e2e/src/cats/cats.controller.ts
- e2e/validate-schema.e2e-spec.ts
- lib/decorators/api-security.decorator.ts
- lib/document-builder.ts
```
[ ] Bugfix
[x] Feature
```
The current api only allows for combining security requirements using logical OR. OpenApi specification also supports combining security requirements using logical AND.
https://swagger.io/docs/specification/authentication/
```ts
@ApiSecurity('key1')
@ApiSecurity('key2')
@Controller('cats')
class CatsController {}
```
```json
{
"security": [
{ "key1": [] },
{ "key2": [] }
]
}
```
Issue Number: #130
```ts
@ApiSecurity({ key1: [], key2: []})
@Controller('cats')
class …
```
> feat: add support for multiple authentication types

- lib/decorators/api-query.decorator.ts
- test/explorer/swagger-explorer.spec.ts
Only add isArray prop to params list when it is an array.
This change is needed to create valid OpenAPI documents.
Closes #1221
```
[x] Bugfix
[ ] Feature
```
Issue Number: #1221 
Add isArray prop for enums on the Api Query decorator when applicable.
This is needed to create valid Open API documentation
```
[ ] Yes
[x] No
```
> fix: add isArray prop for enums on api query decorator when applicable

- e2e/api-spec.json
- e2e/src/cats/cats.controller.ts
- lib/services/swagger-types-mapper.ts
```
[X] Bugfix
[ ] Feature
```
The `enumName` property from the `@ApiParam` decorator is leaking into the Swagger document when an enum is used as a URL parameter. We currently strip the `type` property from the parameter if a schema definition exists but this does not take other decorator properties into account.
Issue Number: #1148 
The `keysToRemove` array has been moved so all methods can access it. If a schema definition exists, we now omit any key featured in the `keysToRemove` array from the …
> fix(#1148): prevent decorator properties from leaking into swagger doc

- lib/plugin/utils/plugin-utils.ts
```
[x] Bugfix
[ ] Feature
```
When using a type provided by a node module the plugin would try to assemble a relative path that led to an error when trying to run the server, on release `4.8.0` an exception was added for the `stream` package, that fix worked only for that specific package, but other packages still were throwing out the same error (refer to issue #1106) 
Issue Number: #1106 
Using `require.resolve(name: string)` we can check if a string is a package, this function throws an error if …
> fix(plugin): check if a importPath is a package

- lib/interfaces/open-api-spec.interface.ts
- test/services/fixtures/create-user.dto.ts
- test/services/schema-object-factory.spec.ts
The definition of 'SchemaObject' currently includes the 'examples' property. However, this property is not valid according to the Open API specification. The typescript compiler does not warn against adding the examples  property, and thus users are able to generate invalid specifications.
[Here ](https://swagger.io/docs/specification/adding-examples/)is the documentation for the examples property. The last line of the section 'Object and Property Examples' states
>  'Note that schemas and properties support single example but not multiple examples.'
-  [x] The commit message follows our guidelines: https://github.com/nestjs/nest/blob/master/CONTRIBUTING.md
```
[x] Bugfix
[ ] Feature
[ …
```
> fix(interfaces): remove 'examples' property

- e2e/api-spec.json
- lib/swagger-module.ts
Ensure that the paths property comes before the components property,
as this may lead to several strange display bugs in swagger-ui.
See swagger-api/swagger-ui#5972 or
https://github.com/swagger-api/swagger-ui/issues/3325#issuecomment-847733645
Closes nestjs/swagger#1369
```
[x] Bugfix
[ ] Feature
```
Issue Number: #1369
```
[ ] Yes
[x] No
```
> fix(@nestjs/swagger) Change created document property order

- e2e/fastify.e2e-spec.ts
- lib/interfaces/swagger-custom-options.interface.ts
- lib/swagger-module.ts
```
[X] Bugfix
[ ] Feature
```
Using `@nestjs/swagger` with Fastify, you cannot pass the `uiConfig` options at `fastify-swagger` plugin registration. 
You can pass on `uiConfig` as per [fastify-swagger's documentation](https://github.com/fastify/fastify-swagger#options). 
```
[ ] Yes
[X] No
```
In order to get there, this PR adds a fourth argument to `setupFastify()` which is the `options: SwaggerCustomOptions` object. This PR also adds the `uiConfig?: Record<string, any>` property to …
> fix(plugin): allow the use of "uiConfig" options to fastify-swagger and Swagger UI

- lib/explorers/api-parameters.explorer.ts
- lib/explorers/api-response.explorer.ts
- lib/services/response-object-factory.ts
- lib/services/schema-object-factory.ts
- lib/swagger-explorer.ts
- lib/swagger-scanner.ts
- test/services/schema-object-factory.spec.ts
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: perf improvement
```
Currently the schemas are passed around with two variables:
- `schemas` of type `Array<{[key: string]: SchemaObject>`
- `schemasRefPaths` which lists the keys
There are a few issues:
- `schemas` is wrongly typed as `SchemaObject[]` in the code
- Two related arguments need to be passed to many function accepting schemas
- To check if an item is already in `schemas`, `schemasRefPaths.includes(key)` is used which is O(schemas.length)
This PR merges …
> perf: store schemas in an object instead of an array of key/value

- lib/decorators/api-response.decorator.ts
set default value for the status code in ApiResponse
decorator if status code  not pass.
```
[x] Bugfix
[ ] Feature
```
Issue Number: #1017
```
[ ] Yes
[x] No
```
> fix: set default status for api-response decorator

- lib/explorers/api-parameters.explorer.ts
- lib/plugin/utils/ast-utils.ts
- lib/plugin/utils/plugin-utils.ts
- lib/plugin/visitors/controller-class.visitor.ts
- lib/plugin/visitors/model-class.visitor.ts
- lib/services/parameters-metadata-mapper.ts
- lib/services/response-object-factory.ts
- lib/services/schema-object-factory.ts
- lib/services/swagger-types-mapper.ts
- lib/swagger-explorer.ts
- lib/swagger-module.ts
- lib/utils/merge-and-uniq.util.ts
- test/plugin/fixtures/string-literal.dto.ts
- test/plugin/model-class-visitor.spec.ts
```
[x] Bugfix
[ ] Feature
```
Single string literal types don't generate a type property metadata, leading to parsing errors.
Ex:
```ts
interface Test { stringLiteral: "one"  }
```
Results in:
```ts
{ stringLiteral: { required: true } }
```
Single string literals get assigned the type of String, ex:
```ts
{ stringLiteral: { required: true, type: () => String } }
```
```
[ ] Yes
[x] No
```
> fix(@nestjs/swagger): Fix generated types for single string literals

- .eslintrc.js
`npm run lint` is broken
```
npm run lint
> @nestjs/swagger@4.8.0 lint
> eslint 'lib/**/*.ts' --fix
Oops! Something went wrong! :(
ESLint: 7.27.0
Error: Cannot read config file: /swagger/node_modules/eslint-config-prettier/@typescript-eslint.js
Error: "prettier/@typescript-eslint" has been merged into "prettier" in eslint-config-prettier 8.0.0. See: https://github.com/prettier/eslint-config-prettier/blob/main/CHANGELOG.md#version-800-2021-02-21
Referenced from: /swagger/.eslintrc.js
at Object.<anonymous> (/swagger/node_modules/eslint-config-prettier/@typescript-eslint.js:1:69)
at Module._compile (/swagger/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
at …
```
> fix: remove prettier/@typescript-eslint from eslint config

- e2e/validate-schema.e2e-spec.ts
- lib/document-builder.ts
- lib/swagger-module.ts
- lib/utils/assign-two-levels-deep.ts
Merge the passed config's components one level deeper, so as to be able to
specify individual schemas that will not be overwritten by the generated document.
Fix #1244
```
[ ] Bugfix
[x] Feature
```
Issue Number: #1244 
`config.components` is merged one level deeper.
There is an alternative solution to #1244 which is to create a new decorator.
```
[x] Yes
[ ] No
```
Schemas, links, examples, responses, ... passed to `SwaggerModule.createDocument` via `config.components` are no longer overwritten if …
> feat(config): merge passed schemas, links, ... in createDocument

- e2e/fastify.e2e-spec.ts
- lib/interfaces/swagger-custom-options.interface.ts
- lib/swagger-module.ts
Allow the use of "initOAuth", "staticCSP" and "transformStaticCSP" options to fastify-swagger
Closes #932
```
[ ] Bugfix
[x] Feature
```
Using @nestjs/swagger with Fastify, you cannot pass the "initOAuth", "staticCSP" and "transformStaticCSP" options at fastify-swagger plugin registration.
Issue Number: #932
You can pass on "initOAuth", "staticCSP" and "transformStaticCSP" as per [fastify-swagger's documentation](https://github.com/fastify/fastify-swagger#options).
```
[ ] Yes
[x] No
```
The existing …
> feat(): add fastify-swagger options

- lib/interfaces/swagger-custom-options.interface.ts
- lib/swagger-module.ts
- lib/swagger-scanner.ts
- lib/utils/get-global-prefix.ts
Added an option in SwaggerModule.setup to use nestjs application global prefix. It is optional and the thefault value is `false`. The default behavior of the application is the same.
```
[ ] Bugfix
[x] Feature
```
The swagger path (first parameter of SwaggerModule.setup function) is not prepended to global prefix set in Nestjs Application.
Example of code:
```ts
const app = await NestFactory.create(AppModule);
app.setGlobalPrefix('my-prefix');
const swaggerConfig = new DocumentBuilder()
.setTitle('My …
```
> feat(@nestjs/swagger): add option in SwaggerModule.setup to use nestjs application global prefix

- lib/extra/swagger-shim.ts
- test/extra/shim.spec.ts
Please check if your PR fulfils the following requirements:
```
[ ] Bugfix
[x] Feature
```
Issue Number: #1037
Developers can use classes decorated with decorators from `@nestjs/swagger` in typescript applications that are run in the browser. This is done by telling either the typescript compiler or a bundler used in the browser application to use the newly added shim file instead of the actual package. The shim file is a lot smaller in size and does not introduce any dependencies on node packages that would otherwise require even larger polyfills.
```
[ ] Yes …
```
> feat(): add shim file for browsers

- lib/plugin/utils/ast-utils.ts
- test/plugin/controller-class-visitor.spec.ts
- test/plugin/fixtures/app.controller-tabs.ts
introspectComments did not properly parse comments when source files used tab indentation
fixes #1705
Issue Number: #1705
> fix: make introspectComments work with tab indentation

- lib/interfaces/swagger-custom-options.interface.ts
Before updating swagger-ui to recent version, we could pass query param to the ui to configure it, such as: `https://swagger-api.com/my-swagger.html?url=a-custom-swagger-document.json`.
Now, it is disabled by default.
It can be activated with option [`queryConfigEnabled`](https://github.com/swagger-api/swagger-ui/blob/master/docs/usage/configuration.md#parameters).
> fix: add missing ui config param 'queryConfigEnabled'

- e2e/api-spec.json
- e2e/fastify.e2e-spec.ts
- e2e/src/app.controller.ts
- e2e/validate-schema.e2e-spec.ts
- lib/interfaces/module-route.interface.ts
- lib/swagger-scanner.ts
- lib/swagger-transformer.ts
```
[X] Bugfix
[ ] Feature
```
Issue Number: #1618
Fixes #1618
```
[ ] Yes
[X] No
```
> fix(): unescape colons in paths

- lib/swagger-module.ts
Fixes: nestjs/swagger#1979
Issue Number: nestjs/swagger#1979
> fix(@nestjs/swagger): skip invalid types when converting swagger document to yaml

- lib/interfaces/swagger-custom-options.interface.ts
- lib/swagger-ui/constants.ts
- lib/swagger-ui/swagger-ui.ts
nestjs/swagger currently doesn't support customJsStr option introduced to swagger-ui-express.
This causes one to use customJs which requires an api endpoint to serve the js file since customJs takes a public url path as input.
Issue Number: #2037
SwaggerCustomOptions now allows for customJsStr to pass javascript as a string equal to customCss.
The provided string is encased in an HTML `<script>` tag and added to the constants html below the other customJs option. 
No test or documentation changes due to look the same as the customJs option.
> Add customJsStr to swagger-custom-options

- lib/swagger-module.ts
- lib/swagger-ui/swagger-ui.ts
- The `swagger-ui-dist` module is loaded before its utilization, and it loads two large files (listed below), causing some overhead on the app initialization (~800ms in a medium app).
- https://github.com/swagger-api/swagger-ui/blob/master/swagger-ui-dist-package/index.js#L2-L3, 
-  https://github.com/swagger-api/swagger-ui/blob/master/dist/swagger-ui-standalone-preset.js
-  https://github.com/swagger-api/swagger-ui/blob/master/dist/swagger-ui-bundle.js
- The `swagger-ui-dist` module is loaded only when serving the Swagger HTML (`SwaggerModule.serveStatic`).
Bubbleprof from Clinicjs using the E2E app.
| Before  | After  | 
|---|---|
| …
> perf(swagger-module): lazy load swagger-ui-dist module

- lib/extra/swagger-shim.ts
- [x ] Bugfix
getSchemaPath is missing in shims.
If you use decorators and also getSchemaPath in ui and use shim, doesnt find the function anymore
- [ x] No
Only for shim. nothing changed
> fix: add getSchemaPath into shim

- lib/services/schema-object-factory.ts
- test/explorer/swagger-explorer.spec.ts
Currently, if you create a number enum property like this:
```typescript
@ApiParam({ enum: [1, 2, 3] })
```
It will then generate a correct schema for this param:
```json
{
"type": "number",
"enum": [1, 2, 3]
}
```
But if you add an “enumName“ parameter, so that the enum will get its own schema entry like this:
```typescript
@ApiParam({ enum: [1, 2, 3], enumName: "ParamEnumName" })
```
It will change the type of the enum in the schema from 'number' to 'string':
```json
{
"ParamEnumName": {
"type": "string",
"enum": [
1,
2,
3
]
}
}
```
I made it so it saves the type, if is was given before.
So if we take our previous example:
```typescript
@ApiParam({ enum: [1, 2, 3], enumName: …
```
> fix: number enum generated schema type

- lib/plugin/visitors/controller-class.visitor.ts
- test/plugin/fixtures/app.controller-without-modifiers.ts
Issue Number: #2153
no empty `ApiOperation` will be emitted.
reserve this: https://github.com/nestjs/swagger/commit/06ec7ec6b5d9393e42f51254e3fdd6ba4dd4425b#diff-d9ab9cd42b694de692963638564f4d9df7a45ccc68838feac4550bd8a61ec1f5L146
> fix(plugin): empty comment do not emit @ApiOperation decorator

- lib/decorators/api-response.decorator.ts
Allow 1XX, 2XX, 3XX, 4XX, 5XX range HTTP response codes.
Only numeric or 'default' HTTP response codes were allowed.
[Range codes](https://swagger.io/docs/specification/describing-responses/) '1XX', '2XX', '3XX', '4XX' and '5XX' are now allowed as well.
- Doc was not updated as there is no doc in this repo.
- No test was added as there does not appear to be a test for `default` either.
> feat(@nestjs/swagger) support HTTP range status codes

- lib/utils/enum.utils.ts
- test/explorer/swagger-explorer.spec.ts
Numeric enums
```ts
enum Size {
SMALL = 1,
BIG = 2,
}
```
are currently displayed as 
```js
['SMALL', 'BIG']
```
Issue Number: #1884
Numeric enums
```ts
enum Size {
SMALL = 1,
BIG = 2,
}
```
should be displayed as 
```js
[1, 2]
```
in schemas and examples.
This is done by fixing the logic which removes reverse mapping.
I consider this more of a bug than a breaking change.
Besides numeric enum, this handles [heterogenous enums](https://www.typescriptlang.org/docs/handbook/enums.html#heterogeneous-enums) as well (not in tests, because Swagger officially supports only enum values of the [same type](https://swagger.io/docs/specification/data-models/enums/)) and keeps the order of keys for …
> fix: fix numeric enum values

- lib/interfaces/swagger-document-options.interface.ts
- lib/swagger-explorer.ts
- lib/swagger-scanner.ts
- test/explorer/swagger-explorer.spec.ts
Adds a new optional parameter to operationIdFactory to allow providing the API version prefix added to the operation's path.
This allows the operationIdFactory to generate unique IDs in the case of the same controller method being used for multiple API versions. Default behavior is unchanged - the operation IDs will be of the form controllerKey_methodKey, but where necessary this can be customised using the URI version prefix.
The implementation here gets the versions that the method is for, and generates the URI prefixes. It then looks for the version prefixes in the paths returned from `RoutePathFactory`, and provides that information to operationIdFactory, so that unique IDs can be generated.
I'm not _super_ familiar with Nest internals, but this looks like the only real way to …
> feat(swagger): Provide URI version to operationIdFactory

- e2e/api-spec.json
- e2e/src/cats/dto/pagination-query.dto.ts
- lib/services/parameter-metadata-accessor.ts
- lib/services/schema-object-factory.ts
- test/services/schema-object-factory.spec.ts
When you add inside of a query parameter an array of enums, the project simply crashes
Issue Number: https://github.com/nestjs/swagger/issues/1096
a full reproduction repo is available by the issue creator https://github.com/murbanowicz/nest-swagger-1096
```
//enum
export enum FooEnum {
BAR = 'BAR',
FOO = 'FOO',
}
//DTO class
class BuggyQueryDTO {
@ApiProperty({
isArray: true,
enum: FooEnum,
enumName: 'buggy',
})
public readonly foos!: FooEnum[];
}
// controller
@Get()
getHello(@Query() query: BuggyQueryDTO): string {
return this.appService.getHello();
}```
The above code will throw error on SwaggerModule.createDocument(app, options);:
```
TypeError: Cannot read property 'items'
of …
```
> fix(core): error when using enum array on api-query

- lib/type-helpers/intersection-type.helper.ts
When using `@nestjs/swagger` with `pnpm` in NestJS application, when `IntersectionType` is used as extension for class, there is dependency error with `@nestjs/mapped-types`. When the intersection is used in `PickType`/`OmitType` or also in this hotfix:
```
const TypeTyper = <T>(classRef: Type<T>): Type<T> => classRef;
```
it behaves normal.
The `Intersection` type (which `IntersectionType` function is using) now returns `Type` instead of `MappedType` which, did nothing greater than wrap the whole type.
> refactor: use Type instead of MappedType

- lib/interfaces/swagger-custom-options.interface.ts
- lib/swagger-module.ts
Currently, NestJS builds the Swagger document synchronously on startup, which it's a waste of time since we don't care about the swagger routes until we need to make a call to it.
So, I added an option to lazy initialize the Swagger document, the document will only be built when we have some request for it.
In my API, it reduced about 70~75ms from initialization, it will vary according to the API and the amount of routes but now it will only take 2ms to initialize the Swagger Module.
Now, to use the new lazy loading feature, just change these lines:
```diff
const swaggerDocument = new DocumentBuilder()
.setTitle(config.get<string>('SWAGGER_TITLE') ?? 'Base') …
```
> perf: added possibility to lazy initialize the document

- .circleci/config.yml
- lib/plugin/utils/plugin-utils.ts
- lib/plugin/visitors/abstract.visitor.ts
- lib/plugin/visitors/controller-class.visitor.ts
- lib/plugin/visitors/model-class.visitor.ts
> chore: drop support for typescript < 4.8

- e2e/express.e2e-spec.ts
- e2e/fastify.e2e-spec.ts
- lib/swagger-ui/swagger-ui.ts
Options passed to `SwaggerModule.setup` are ignored. The `customOptions` object passed to `buildSwaggerHTML` is malformatted. Custom parameters that should be contained within the base of `customOptions` are actually contained within `swaggerOptions`, which itself contains another object `swaggerOptions`. For example, this is the object passed to `buildSwaggerHTML` when you run `npm run start:dev`:
```js
{
jsonDocumentUrl: '/api-docs-json',
yamlDocumentUrl: '/api-docs-yaml',
swaggerOptions: {
customSiteTitle: 'Demo API - Swagger UI 1',
swaggerOptions: {
persistAuthorization: true,
defaultModelsExpandDepth: -1,
syntaxHighlight: [Object],
tryItOutEnabled: true
},
customfavIcon: …
```
> fix: issue where custom assets are not injected in html

- e2e/express.e2e-spec.ts
- e2e/fastify.e2e-spec.ts
- e2e/manual-e2e.ts
- lib/interfaces/swagger-custom-options.interface.ts
- lib/swagger-module.ts
It is impossible to patch the document after it is generated and before it is served.
Issue Number: #2502
A new option `patchDocument` can be passed to `SwaggerModule.setup`.
```typescript
SwaggerModule.setup("/:tenantId/api-docs", app, document, {
patchDocument: (req: Request, res: Response, document1: OpenAPIObject) => ({
...document1,
info: {
...document1.info,
title: `${req.params.tenantId}'s API document`
}
})
})
```
- [ x ] No
> Support changing the OpenAPI document based on the request

- e2e/express.e2e-spec.ts
- e2e/fastify.e2e-spec.ts
- lib/interfaces/swagger-custom-options.interface.ts
- lib/swagger-module.ts
- lib/utils/resolve-path.util.ts
Issue Number: https://github.com/nestjs/swagger/issues/2543
Adds the ability to override the default location `swagger-ui-dist`. This is useful when using, for example, `webpack`.
https://github.com/nestjs/docs.nestjs.com/pull/2813
> feat: add `customSwaggerUiPath`

- e2e/api-spec.json
- e2e/src/cats/dto/pagination-query.dto.ts
- lib/services/swagger-types-mapper.ts
When setting an object with a pre-defined list of properties as a Query-argument, the generated OpenAPI schema will have the `properties` key outside of the `schema` definition. This violates the OpenAPI spec.
https://github.com/addono/swagger/blob/038a366548beac5ffd392508e43225722d2184c6/e2e/api-spec.json#L362-L369
The `properties`-field is kept as a child of the `schema`-key.
https://github.com/Addono/swagger/blob/1e9a3386228e0bcb229027901e415b476dda7272/e2e/api-spec.json#L362-L373
This PR contains two commits:
- First commit adds an example to the E2E tests which show how the generated spec is failing. For this commit, the E2E tests fail. This commit is there to …
> fix: support defining `properties` for query-arguments of type objects

- lib/interfaces/swagger-document-options.interface.ts
- lib/swagger-explorer.ts
- lib/swagger-scanner.ts
- test/explorer/swagger-explorer.spec.ts
This is based on the work completed in #1949. Those changes were reverted due to test failures.
This change adapts those changes to also support neutral versions which resolves the test failures.
Adds a new optional parameter to operationIdFactory to allow providing the API version prefix added to the operation's path.
This allows the operationIdFactory to generate unique IDs in the case of the same controller method being used for multiple API versions.
Default behavior is unchanged - the operation IDs will be of the form controllerKey_methodKey, but where necessary this can be customised using the URI version prefix.
Closes nestjs#2537
When using Nest's API versioning feature, and …
> feat(swagger): Provide URI version to operationIdFactory 

- lib/plugin/utils/ast-utils.ts
- lib/plugin/utils/plugin-utils.ts
- test/plugin/fixtures/project/cats/classes/cat.class.ts
- test/plugin/fixtures/serialized-meta.fixture.ts
String mappings like `Uppercase<string>` or `Lowercase<string>` are not recognized as string type.
Issue Number: #2606
String mappings are recognized as string type.
Closes #2606
> feat: add support for string mapping types

- lib/services/schema-object-factory.ts
- test/services/schema-object-factory.spec.ts
If an enum property is decorated with `isArray: true`, its type should be derived from the type of the enum item, rather than as an `array`.
Issue Number: https://github.com/nestjs/swagger/issues/2615
Enum schemas should now use the type of enum itself, regardless of whether it was declared as an array or not.
> fix(): Derive enum types correctly when defined as an array #2615

- lib/swagger-module.ts
I don't think tests or docs changes are needed, but let me know if you disagree.
The generated Yaml specification includes [content refs](https://lzone.de/cheat-sheet/YAML#content-references-aliases) at seemingly arbitrary places. While this is a perfectly valid Yaml, some of the tools may not be able to deal with this (e.g. Redocly preview in the WebStorm) and it makes the file harder to read or diff because one does not control where references are used in the generated specification.
The library is configured to not use content refs in the generated Yaml specification.
Example:
```diff
/resources:
post:
operationId: create
parameters: []
requestBody:
required: true …
```
> feat: Disable refs in the generated Yaml file

- e2e/api-spec.json
- e2e/src/cats/dto/create-cat.dto.ts
- lib/document-builder.ts
- lib/services/schema-object-factory.ts
- test/services/schema-object-factory.spec.ts
Closes https://github.com/nestjs/swagger/issues/2683
Issue Number: #2683
It adds a `DocumentBuilder.addExtension()` method and allows the existing `ApiExtension` annotation to be used on Schema objects.
> feat(@nestjs/swagger): Support extensions in Document and Schema objects

- lib/plugin/merge-options.ts
- lib/plugin/visitors/model-class.visitor.ts
- test/plugin/fixtures/parameter-property.dto.ts
- test/plugin/model-class-visitor.spec.ts
Parameter properties are not supported.
Issue Number: #2056
Basic support for parameter properties is added.
The feature is controlled by the `parameterProperties` option, which is disabled by default. As the feature is opt-in, it should be possible to release it as a minor version.
Worth noting, that using parameter properties has some limitations compared to the regular properties, but it can still be useful for some basic scenarios.
1. Can't use validation annotations as it is not supported by the class-validator - https://github.com/typestack/class-validator/issues/1669.
2. Can't use JSDoc tags, e.g. `@example` or `@deprecated`. Parsing description from the comment is not …
> feat: Add basic support for parameter properties

- lib/decorators/api-param.decorator.ts
- lib/decorators/api-query.decorator.ts
- lib/decorators/helpers.ts
- lib/swagger-ui/helpers.ts
- test/decorators/api-param.decorator.spec.ts
- test/decorators/api-query.decorator.spec.ts
- test/explorer/swagger-explorer.spec.ts
Support added of ApiParam and ApiQuery for Controller, PR Reference #1332
Put ApiParam on every route method in controller.
```
@Controller('tests/:testId')
class TestAppController {
@ApiParam({ name: 'testId' })
@ApiQuery({ name: 'testQuery'})
@Get()
public method1(@Param('testId') testId: string, @Query('testQuery') testQuery: string) {
}
@ApiParam({ name: 'testId' })
@ApiQuery({ name: 'testQuery'})
@Get()
public method2(@Param('testId') testId: string, @Query('testQuery') testQuery: string) {
}
}
```
Issue Number: #2200
I would like ApiParam to support the class decorator to reduce the waste of time.
```
@ApiParam({ name: 'testId' }) //new
@ApiQuery({ name: 'testQuery'}) //new …
```
> feat: Support of ApiParam and ApiQuery for Controller

- e2e/api-spec.json
- e2e/express.e2e-spec.ts
- e2e/fastify.e2e-spec.ts
- e2e/src/cats/classes/cat.class.ts
- e2e/src/cats/dto/create-cat.dto.ts
- e2e/validate-schema.e2e-spec.ts
- lib/services/schema-object-factory.ts
If there is an `enumName` supplied, all the additionalFields are currently just added as a ref-sibling. This is not swagger-spec compliant and therefore gets ignored.
See this issue for more information: https://github.com/nestjs/swagger/issues/2806
> feat(spec): allow additional fields on enum refs

- lib/plugin/utils/plugin-utils.ts
- test/plugin/fixtures/create-cat.dto.ts
Using the `UUID` type from node's `crypto` package with the `@nestjs/swagger` plugin enabled crashes nestjs start `npm run start` with a cryptic error message.
```
Error: A circular dependency has been detected (property key: "id"). Please, make sure that each side of a bidirectional relationships are using lazy resolvers ("type: () => ClassType").
```
Example dto
```
import { UUID } from 'crypto';
export class CreateUserDto {
name: string;
id: UUID;
}
```
This problem goes away when the `IsUUID()` decorator from `class-validator` package is used. But considering the fact that UUID is an alias ```type UUID = `${string}-${string}-${string}-${string}-${string}`;``` the inferred type …
> fix: support type `UUID` from node's `crypto` package

- lib/decorators/api-response.decorator.ts
- lib/extra/swagger-shim.ts
No decorator to add documentation about response with HTTP status [402 Payment required](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/402)
Added the decorator `@ApiPaymentRequiredResponse`
> feat(core): add decorator for reponse http status 402 : ApiPaymentRequiredResponse

- lib/type-helpers/partial-type.helper.ts
- test/type-helpers/partial-type.helper.spec.ts
`PartialType` will return a class for which validations are ignored `null` properties (in addition to `undefined` properties).
Issue Number: [2843](https://github.com/nestjs/swagger/issues/2843), [2623](https://github.com/nestjs/swagger/issues/2623)
`PartialType` can optionally return a class for which validations are ignored only for `undefined` properties, not `null` properties. This can be useful if you are creating a DTO for a PATCH endpoint: there may be a certain field, say `name`, that should not be `null`, but which doesn't need to be included in PATCH updates.
This is actually just a copy-paste of the same PR to mapped-types repo: …
> feat: add skip null properties option to partial type

- lib/extra/swagger-shim.ts
When using `refs` in the frontend code with shim file used it fails because of missing refs export - of course if that was used.
No fail
> fix: add missing refs declaration in swagger-shim

- lib/services/schema-object-factory.ts
- test/services/fixtures/create-profile.dto.ts
Issue Number: #2951 
Setting the `name` property no longer results in a `$ref` being wrapped in `allOf`.
> fix: Retain $ref when setting name property

- lib/decorators/api-property.decorator.ts
- lib/utils/enum.utils.ts
- test/explorer/swagger-explorer.spec.ts
- test/services/schema-object-factory.spec.ts
When using enum values that are dynamic, the value returned depends on the order that modules are imported in 
Issue Number: https://github.com/nestjs/swagger/issues/2786
enum can be a function which is called at the moment that the document is generated.
> feat: add function for enum types

- lib/plugin/utils/plugin-utils.ts
- test/plugin/fixtures/app.controller.ts
I've encountered an issue with NestJS Swagger where automatic API documentation generation does not properly handle types that include the `Promise` or `Observable` keywords. This occurs when using `@Body()`, `@Query()`, or return types in controllers that are intended to be documented by Swagger.
Types that include `Promise` or `Observable` should be accurately reflected in the Swagger documentation.
> fix(plugin): ensure open-api docs generation for types named with Promise or Observable

- e2e/express.e2e-spec.ts
- lib/interfaces/swagger-custom-options.interface.ts
- lib/swagger-module.ts
- lib/swagger-ui/swagger-ui.ts
Issue Number: none
Currently when using `SwaggerModule.setup` it serves all files of Swagger UI and API definitions generated on the fly (JSON and YAML). It isn't possible for now to only serve API definitions.
I see two uses-cases for this feature:
- You want to serve multiple API definitions in your Nest application, so you might want to enable the UI only for the "default" API and disable it for other ones.
- You already have a Swagger UI served somewhere else in your infrastructure and just want to make it point the API definition of your Nest app. So the UI might be disabled to reduce noise.
This PR introduces a way to disable the Swagger UI to only generate API definitions.
A new …
> feat: allow to disable Swagger UI

- lib/services/schema-object-factory.ts
Issue Number: #3061
Class ApiProperties must be mapped as in: "path" when used in type of ApiParam
> fix: correct ApiParam type as in: path

- lib/decorators/api-header.decorator.ts
Closes #3036
Setting the `examples` field in `@ApiHeader` will produce the example dropdown for that field in the swagger docs.
> Support `examples` field in `@ApiHeader`

- e2e/api-spec.json
- e2e/src/cats/dto/pagination-query.dto.ts
- lib/services/swagger-types-mapper.ts
- test/plugin/fixtures/project/cats/dto/pagination-query.dto.ts
Currently, the `example` annotation is not correctly copied into the `schema` object.
See https://swagger.io/docs/specification/adding-examples/.
Refer to:
https://github.com/nestjs/swagger/blob/02e03411f7823362247cdf0de0e185657ace2069/lib/services/swagger-types-mapper.ts#L114-L124
and
https://github.com/nestjs/swagger/blob/02e03411f7823362247cdf0de0e185657ace2069/lib/services/swagger-types-mapper.ts#L140-L161
Example annotations/properties are now correctly copied.
> feat: Add schema support for "example" annotations

- lib/document-builder.ts
Today, the OpenApi Spec version is hard coded at lib/fixtures/document.base.ts and there's no way to change it.
Issue Number: https://github.com/nestjs/swagger/issues/2361
Creates a new method at the DocumentBuilder called setOpenApiVersion that receives a string, checks if its a valid OpenApi Spec Version and if so override the default versions previously defined.
The PR reopens https://github.com/nestjs/swagger/pull/2516 as it was closed before being merged.
> feat(document-builder): add setOpenApiVersion method

- lib/services/schema-object-factory.ts
- test/explorer/swagger-explorer.spec.ts
- test/services/schema-object-factory.spec.ts
```
[x] Bugfix
[ ] Feature
```
See https://github.com/nestjs/swagger/issues/1112
Arrays and objects are now correctly interpreted as such in @Query()
```
[ ] Yes
[x] No
```
> fix: Arrays and objects are not managed properly when located in first level of @Query()

- lib/decorators/api-header.decorator.ts
As outlined in the issue [2761](https://github.com/nestjs/swagger/issues/2761): The schema is being overwritten in apiHeader if an enum is provided. 
A demo repo with instructions can be found at https://github.com/eugleenyc/swagger-fix-demo/
How to see the defect:
- clone the repo https://github.com/eugleenyc/swagger-fix-demo/
- run `npm install`
- run `npm start`
- go to `http://localhost:3000/yaml`
The resulting yaml will show the following:
```
openapi: 3.0.0
paths:
/:
get:
operationId: AppController_getHello
parameters:
- name: testHeader
required: true
in: header
description: test description
schema:
enum:
- an enum
type: string
responses:
'200':
description: ''
info:
title: demo …
```
> fix enum schema

- e2e/api-spec.json
- e2e/src/cats/cats.controller.ts
- e2e/src/cats/classes/cat.class.ts
- e2e/src/cats/dto/create-cat.dto.ts
- lib/decorators/api-param.decorator.ts
- lib/decorators/api-property.decorator.ts
- lib/decorators/api-query.decorator.ts
- lib/interfaces/enum-schema-attributes.interface.ts
- lib/interfaces/schema-object-metadata.interface.ts
- lib/services/parameter-metadata-accessor.ts
- lib/services/schema-object-factory.ts
- lib/services/swagger-types-mapper.ts
- lib/utils/enum.utils.ts
- test/explorer/swagger-explorer.spec.ts
- test/services/schema-object-factory.spec.ts
Issue Number: #2898 #3101
Instead of auto-populating field attributes to the enum schema, allow field-specific attributes and introduce the `enumSchema` property to allow setting Enum's default, deprecated, description, and other attributes.
> feat: introduce enum schema attribute

- lib/plugin/merge-options.ts
- test/plugin/fixtures/create-option.ts
- test/plugin/merge-option.spec.ts
Issue Number: #2958
When using the cli-plugin, it does not recognize the file for controller when the dtoFileNameSuffix option contains “.ts”.
When using the cli-plugin, if the dtoFileNameSuffix option contains “.ts”, omit the “.ts”.
It also leaves a warning log.
> fix(@nest/swagger): Add merge-options condition for dtoFileNameSuffix to CLI-Plugin

- e2e/api-spec.json
- e2e/src/cats/cats.controller.ts
- e2e/validate-schema.e2e-spec.ts
- lib/swagger-transformer.ts
```
[x] Bugfix
[ ] Feature
```
@ApiOperation.responses was disregarded as the auto-detected responses were given preference. Auto-detection happens always, even if no return type is configured.
Issue Number: #1420
Explicit config is given preference over auto-detected schema
```
[ ] Yes
[x] No
```
This PR only fixes the issue on a smaller level, however there is a scope for improving how the actual merging should happen for the schema extracted from different areas.
Each schema extracted should be …
> fix(transformer): prefer explicit config over auto-detected schema

- lib/decorators/api-response.decorator.ts
- test/decorators/api-response.decorator.spec.ts
Decorators like ApiOkResponse always override the status to a specific code. 
Devs might think they are overriding the status but it's actually a no-op. 
Updated the types of the options to raise an error if status is passed.
Someone specifying a method like
```ts
@Controller('tests/:testId')
class TestAppController {
@Get()
@ApiOkResponse({ status: 201 })
public get(@Param('testId') testId: string): string {
return testId;
}
}
```
Might think it will return a 201 response, But it's easy to miss the `Ok` in `ApiOkResponse` vs `ApiResponse`
The code above will not compile because `status` is no longer an accepted option for Response decorators that override the status …
> fix(): Updated types for Specific ApiResponse decorator options to omit status

- lib/plugin/utils/plugin-utils.ts
- lib/plugin/visitors/controller-class.visitor.ts
- lib/plugin/visitors/model-class.visitor.ts
Currently compiler option paths never take the base path into the account when resolving dependencies (as introduced in #3134). In certain configurations this can lead to errors as we always join the resolved path with the source file path.
This is likely causing issues in #3154.
Compiler option paths are resolved to base path if declared as relative.
> fix(plugin): resolve compiler option paths relative to base

- lib/services/schema-object-factory.ts
- lib/utils/get-schema-path.util.ts
- test/services/schema-object-factory.spec.ts
Ensure the correct @ApiSchema name is used when inheriting from a base class.
Issue Number: #3160
The correct schema name will be used
There's also a fix necessary for `getSchemaPath` (get-schema-ath.util.ts). However I have not found a single test for these utils, so I didn't add one but applied the exact same fix.
> fix: @ApiSchema inheritance

- e2e/api-spec.json
- e2e/src/cats/classes/cat.class.ts
- e2e/validate-schema.e2e-spec.ts
- lib/decorators/helpers.ts
Support multiple `@ApiExtension` decorators on the schema class. This implementation applies the same fix as #1525 but also for the class, not just for the member functions.
This enables you do use multiple `@ApiExtension` (and other mixed decorators) on an API schema definition like this:
```ts
@ApiExtension('x-foo', { test: 'test' })
@ApiExtension('x-bar', { test: 'test' })
class CatDto {
}
```
Currently it is not possible to use the same decorator multiple times on the same class. I.e. using two `@ApiExtension()` decorators will only result in the first one being applied.
This PR fixes this behavior and applies all decorators as expected. It implements the same fix …
> fix: support for multiple api decorators on schema class

- e2e/express.e2e-spec.ts
- e2e/fastify.e2e-spec.ts
- lib/interfaces/swagger-custom-options.interface.ts
- lib/swagger-module.ts
Currently, the Swagger module always serves both Swagger UI and JSON/YAML API definitions. There is no way to selectively disable one or the other.
Issue Number: #3157 
This PR introduces two new options to provide greater control over Swagger endpoints:
swaggerUiEnabled: If false, the Swagger UI will not be served.
documentsEnabled: If false, JSON and YAML API definitions will not be served.
Developers can now:
1. Disable the Swagger UI but retain JSON/YAML definitions.
2. Disable JSON/YAML definitions but retain the Swagger UI.
3. Completely disable all Swagger-related endpoints.
These changes enhance the flexibility and security of Swagger integration, enabling better alignment with …
> feat(swagger): add documentsEnabled option to disable JSON/YAML

- e2e/api-spec.json
- e2e/src/cats/dto/extra-model.dto.ts
- lib/decorators/api-schema.decorator.ts
- lib/services/schema-object-factory.ts
- test/services/schema-object-factory.spec.ts
Related PR to update docs can be found here: 
- https://github.com/nestjs/docs.nestjs.com/pull/3157
Issue Number: [2671](https://github.com/nestjs/swagger/issues/2671)
When using the `@ApiSchema` decorator, it is now possible to specify the model's description.
```ts
@ApiSchema({ description: "Model Description"})
class Model {
// ...
} 
```
When rendering the openapi spec, the description will be added to document like this:
```jsonc
{
// ...
"schemas": {
"Model": {
"type": "object",
"description": "Model Description"
//...
}
}
// ...
}
```
> feat: support description in @ApiSchema

- lib/services/parameter-metadata-accessor.ts
> fix: swagger crashed while using any Param/Query/Body decorator in a monorepo with pnpm

- lib/plugin/utils/plugin-utils.ts
- test/plugin/fixtures/parameter-property.dto.ts
- test/plugin/fixtures/serialized-meta.fixture.ts
NestJS does not officially support ESM. I have a project that successfully uses ESM with a custom fork, but in this Swagger plugin, the only incompatibility I found is that the generated code uses `require` without file extensions.
- Prior to Node.js 22, `require` could not import ES modules.
- As of Node.js 22, `require` can import ES modules, but missing file extensions continue to cause issues.
This PR adds the appropriate file extension in the generated code based on the input extension (.cts, .mts, or .ts), thereby improving compatibility with ESM.
I am a new NestJS user who has integrated it into an existing ESM-based project. Currently, I rely on a monkey-patch …
> feat: make generated require() ESM compatible

- e2e/api-spec.json
- lib/services/swagger-types-mapper.ts
When a parameter is specified as an array, the `type` and `items` of the parameter are not currently rendered in the schema. E.g.
```
@ApiProperty({
name: '_sortBy',
nullable: true,
})
sortBy: string[];
```
produces
```
- name: _sortBy
- in: query
- required: true
- schema:
- nullable: true
```
This is not valid OpenAPI 3.0. 
`type` and `items` are specified in the schema.
```
- name: _sortBy
- in: query
- required: true
- schema:
- nullable: true
- type: array
- items:
- type: string
```
This conforms to the OpenAPI 3.0 spec as described here for how arrays should be serialized in the url: https://swagger.io/docs/specification/v3_0/serialization/#serialization-and-rfc …
> feat: Add schema support for array items

- lib/services/decorators-properties.ts
- test/plugin/fixtures/create-cat.dto.ts
This PR corrects class-validator property decorator name IsUuid to IsUUID. ([Reference](https://www.npmjs.com/package/class-validator#validation-decorators) class-validator decorators)
Currently IsUUID decorator from class-validator is not adding {pattern: uuid} in the generated swagger property.
Using IsUUID decorator from class-validator now adds {pattern: uuid} in the generated swagger property.
> fix: incorrect IsUuid class-validator decorator

- lib/interfaces/swagger-ui-options.interface.ts
Currently, `SwaggerUiOptions` does not include the `persistAuthorization` property, which is a valid option in Swagger UI.
This causes TypeScript users to not receive autocomplete and type safety for this option.
This PR adds `persistAuthorization` to the `SwaggerUiOptions` interface, allowing TypeScript users to use this option with proper type inference.
Swagger UI documentation confirms that `persistAuthorization` is a valid option.
Reference: https://swagger.io/docs/open-source-tools/swagger-ui/usage/configuration/
> fix(swagger-options): add persistAuthorization to SwaggerUiOptions

- lib/interfaces/open-api-spec.interface.ts
- lib/services/schema-object-factory.ts
```
export enum StatusEnum {
APPROVED = 1,
PENDING,
REJECTED,
}
export class Meeting {
name: string;
@ApiProperty({
description: 'The status of the meeting',
enum: StatusEnum,
enumName: 'StatusEnum',
'x-enumNames': ['APPROVED', 'PENDING', 'REJECTED'],
})
status: StatusEnum;
}
```
```
"components": {
"schemas": {
"StatusEnum": {
"type": "number",
"enum": [
1,
2,
3
]
},
"Meeting": {
"type": "object",
"properties": {
"status": {
"description": "The status of the meeting",
"x-enumNames": [
"APPROVED",
"PENDING",
"REJECTED"
],
"allOf": [
{
"$ref": "#/components/schemas/StatusEnum"
}
]
},
"name": {
"type": "string"
}
},
"required": [
"status",
"name"
]
}
}
```
x-enumNames no longer works …
> fix(swagger): added options in createEnumSchemaType

- lib/plugin/visitors/model-class.visitor.ts
- test/plugin/fixtures/create-cat-alt.dto.ts
- test/plugin/fixtures/create-cat-alt2.dto.ts
- test/plugin/fixtures/create-cat.dto.ts
Issue Number: [!3322](https://github.com/nestjs/swagger/issues/3322)
Private properties of a class are omitted now, so they do not cause the `SyntaxError`.
> feat: support native private class properties in model class visitor

- e2e/api-spec.json
- e2e/src/cats/classes/cat.class.ts
- e2e/src/cats/dto/create-cat.dto.ts
- e2e/validate-schema.e2e-spec.ts
- lib/services/schema-object-factory.ts
When using `@ApiProperty({ type: 'object', selfRequired: false })` on an object (which is enforced by types, `required: false` cannot be used on an object as it refers to its own properties), the property is added to the list of `required` properties. This is a bug.
Setting `selfRequired: false` on a object-type property does work, and the property is not added to the list of `required`. This is implemented by having `selfRequired` taking precedence over `required`, as `selfRequired` is non-ambiguous about its intent (it can only be used for object types, with the clear meaning of applying to the decorated property).
Related to #3163.
> Fix `selfRequired: false` not making an object-type property optional

- lib/plugin/utils/plugin-utils.ts
- test/plugin/fixtures/parameter-property.dto.ts
Issue Number: https://github.com/nestjs/swagger/pull/3362
Fixing errors in the environment that were not tested in the previous PR.
- ✅ commonjs
- ✅ esm + swc
- ❌ esm + tsc
- ✅ esm + tsc
The format of the output when building in `swc` and `tsc` is different.
`swc` converts `require` to `import` in the metadata, but `tsc` does not.
**tsc**
```js
__decorate([
Get('memo/:id'),
openapi.ApiResponse({ status: 200, type: require("../entities/test/memo.entity.js").Memo }),
__param(0, Param('id', ParseIntPipe)),
__metadata("design:type", Function),
__metadata("design:paramtypes", [Number]),
__metadata("design:returntype", Promise)
], SampleController.prototype, "read", null);
```
**swc**
```js …
```
> fix: import handling for ESM compatibility

- lib/services/schema-object-factory.ts
- test/services/schema-object-factory.spec.ts
Issue Number: https://github.com/nestjs/swagger/issues/3398
Whenever a dto with the same name and different schema is detected, an error would be thrown.
Projects with duplicate DTO names with different schemas will have to adjust the duplicate dtos.
> feat(schema): add duplicate DTO detection in schema exploration

- lib/plugin/utils/plugin-utils.ts
- test/plugin/fixtures/parameter-property.dto.ts
Issue Number: https://github.com/nestjs/swagger/pull/3399
Fixes an issue where the `esmCompatible` option in the swagger plugin fails to load the `ApiResponse` type when using `tsc`.
- ✅ esm + swc
- ❌ esm + tsc
- ✅ esm + tsc
> fix: type import syntax for ApiResponse in esmCompatible

- lib/plugin/merge-options.ts
- lib/plugin/visitors/model-class.visitor.ts
- test/plugin/fixtures/create-option.ts
- test/plugin/model-class-visitor.spec.ts
When using @ApiProperty({ enum: SubjectEnum, enumName: 'Subject' }) readonly __caslSubjectType__: SubjectEnum = this.constructor.name as SubjectEnum;, the generated OpenAPI schema always includes:
```
"__caslSubjectType__": {
"default": "Function",
"allOf": [
{ "$ref": "#/components/schemas/Subject" }
]
}
```
There is no built-in way to omit that default unless you explicitly set default: null.
Issue Number: #3338 
Introduce a skipDefaultValues option on the Swagger plugin.
Default: skipDefaultValues: false (existing behavior)
When enabled: any property without an explicit default initializer will not have a default field in the schema.
Example – with skipDefaultValues: true:
``` …
```
> feat(swagger-plugin): add skipDefaultValues option to omit unspecified default fields and corresponding test

- lib/interfaces/open-api-spec.interface.ts
SecuritySchemes cannot include additional necessary information. Specifically, for security implementations requiring more than one header, the current `Security Scheme Object` cannot represent such configurations. This limitation makes it difficult to express security setups for platforms like AWS API Gateway, which often require additional metadata.
Issue Number: #3179 
Added support for custom extension properties in the `SecuritySchemeObject`
example code when used `addApiKey()`
```
.addApiKey({
type: 'apiKey',
name: 'Authorization',
in: 'header',
'x-amazon-apigateway-authtype': 'oauth2',
'x-amazon-apigateway-authorizer': {
type: 'token',
authorizerUri: …
```
> feat(swagger): add extension in SecuritySchemeObject

- e2e/api-spec.json
- e2e/validate-schema.e2e-spec.ts
- lib/document-builder.ts
- lib/interfaces/open-api-spec.interface.ts
Currently, the extensions are only allowed at root level of the openapi document. According to the [OpenAPI documentation](https://swagger.io/docs/specification/v3_0/openapi-extensions/), there are more sections where this extensions can be added.
In my case, I want to add Redocly extensions like the [x-logo](https://redocly.com/docs-legacy/api-reference-docs/specification-extensions/x-logo#x-logo) that is supposed to go inside the info section.
Adds a new parameter to the `addExtension` method (default to `root`) that also allows setting extensions inside the info section.
OpenApi extensions documentation - https://swagger.io/docs/specification/v3_0/openapi-extensions/
Redocly Info …
> feat(document-builder): add support for setting extensions inside the info object
