nestjs/swagger

- lib/explorers/api-parameters.explorer.ts
Isolated commits of the previous pull request (nestjs/swagger#2)
> Correctly referencing an array of complex object

- lib/explorers/api-security.explorer.ts
- lib/explorers/api-use-tags.explorer.ts
> Bug fixes ( Issues #35, #70)

- lib/explorers/api-response.explorer.ts
- package-lock.json
- package.json
```
[x] Bugfix
[ ] Feature
```
Currently the @ApiResponse decorator does not honor the isArray: true metadata attribute when a primitive type is specified (i.e. String).  
For example, given the following decorator.
```
@ApiResponse({
status: 200,
description: "A list of roles that can be used on the site",
type: String,
isArray: true
})
```
The following schema element is rendered.
```
schema: {
type: 'string'
}
```
The correct rendering should be...
```
schema: {
type: 'array'
items: {
type: 'string' …
```
> Update api-response.explorer.ts to properly reflect arrays of primatives

- lib/decorators/api-operation.decorator.ts
- package-lock.json
- package.json
Hi
I added the `deprecated` param to an api operation.
`@ApiOperation({ title: 'Create dog', deprecated: true })`
Default to false.
> add deprecated param to operation model

- lib/document-builder.ts
- lib/fixtures/document.base.ts
```
[x] Bugfix
[ ] Feature
```
The button is now hidden when no authentication method is set up.
The button is now hidden when no authentication method is set up.
```
[ ] Yes
[x] No
```
> Fix auth button visibility

- lib/explorers/api-response.explorer.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> feature: add status response

- package-lock.json
- package.json
upgrade to the last swagger UI version (less bug in UI rendering, i.e. objects with key named "properties" used in GEOJSON standard are now rendered correctly, there was a conflict between swagger keyword proprieties and object key properties)
```
[x] Bugfix
[ ] Feature
[x] Build related changes
```
```
[ ] Yes
[x] No
```
> build:upgrade to latest swagger UI version

- lib/swagger-module.ts
```
[ ] Bugfix
[ ] Feature
[x] Build related changes
```
```
[ ] Yes
[*] No
```
This PR based on https://github.com/nestjs/nest/commit/e4179eb380e8d2c8e7bd7756f0d9c326d9479e50
> enhancement() use loader function 

- .gitignore
- package-lock.json
- package.json
- test/explorer/explore-controllers.spec.ts
[x] Build related changes
There are no tests 😱 
It adds one so that further contributions can be easily added.
[x] No
@kamilmysliwiec it very likely requires you to enable Travis on this repository; could you do so? 🙃
> Add the very first test

- lib/services/schema-object-factory.ts
- test/services/schema-object-factory.spec.ts
```
[x] Bugfix
[ ] Feature
```
Wrong usage of `$ref` for nested schema. Current behavior: `schema.$ref`
Issue Number: #369 
just `$ref` instead of `schema.$ref`.
```
[ ] Yes
[x] No
```
> [next] Fix nested schema

- lib/decorators/api-property.decorator.ts
- package.json
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix() add missing properties support (response model)

- e2e/src/cats/cats.controller.ts
- lib/services/schema-object-factory.ts
```
[x] Bugfix
[ ] Feature
```
Issue Number: #374 
`@ApiOperation` can now handle lazy-evaluated-type-functions.
```
[ ] Yes
[x] No
```
> Fix @ApiOperation cannot handle lazy-evaluated-type-function

- lib/interfaces/open-api-spec.interface.ts
```
[X] Bugfix
[ ] Feature
```
Issue Number: #403
```
[ ] Yes
[X] No
```
> fix(): fix interface | issue #403

- lib/decorators/helpers.ts
- test/services/schema-object-factory.spec.ts
The schema from the the base class is not being correctly updated when a
sub class overrides a property
The existing schema and the new schema is not being merged properly (missing spread operator) and the merge order is reversed, the existing schema should be merged first in order to keep the updates from the new schema
The error below is the error thrown by the test I've implemented without any further code modification
```
Error: A circular dependency has been detected (property key: "name"). Please, make sure that each side of a bidirectional relationships are using lazy resolvers ("type: () => ClassType").
at SchemaObjectFactory.createNotBuiltInTypeReference (/home/user/workspace/github/swagger/lib/services/schema-object-factory.ts:189:13)
at …
```
> fix(): override base class metadata with the metadata from the sub class

- lib/type-helpers/index.ts
- lib/type-helpers/intersection-type.helper.ts
- test/type-helpers/intersection-type.helper.spec.ts
see nestjs/graphql#776
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(@nestjs/swagger): add `IntersectionType` helper

- lib/decorators/index.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(): missed api-cookie.decorator export

- lib/decorators/api-header.decorator.ts
- lib/decorators/helpers.ts
- lib/document-builder.ts
- lib/explorers/api-parameters.explorer.ts
- lib/plugin/compiler-plugin.ts
- lib/services/mimetype-content-wrapper.ts
- lib/services/parameters-metadata-mapper.ts
- lib/swagger-scanner.ts
- lib/swagger-transformer.ts
- lib/utils/get-schema-path.util.ts
- lib/utils/is-built-in-type.util.ts
```
[ ] Bugfix
[ ] Feature
[x] Code style update (formatting, local variables)
```
```
[ ] Yes
[ ] No
```
> chore(lib): run format and lint

- lib/decorators/api-response.decorator.ts
```
[ ] Bugfix
[x] Feature
```
No shorthand decorator for the 412 Precondition Failed HTTP API response.
Added a shorthand decorator for 412 Precondition failed.
This is related to https://github.com/nestjs/nest/pull/5116
```
[ ] Yes
[x] No
```
> feat(): add shorthand decorator for precondition failed

- e2e/api-spec.json
- e2e/src/cats/dto/pagination-query.dto.ts
- lib/services/swagger-types-mapper.ts
- (seems nothing needed to be updated)
```
[x] Bugfix
[ ] Feature
```
`additionalProperties` in `ApiProperty` is not moved to `schema` in swagger.json, which is invalid
shouldm move `additionalProperties` to `schema`
```
[ ] Yes
[x] No
```
> fix: includes additional properties in schema

- CONTRIBUTING.md
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: Doc change
```
```
[ ] Yes
[x] No
```
This change reflects the main repo's [CONTRIBUTING.md](https://github.com/nestjs/nest/blob/master/CONTRIBUTING.md#rules)
> docs(contributing): remove broken link to docs/DEVELOPER.md

- lib/interfaces/open-api-spec.interface.ts
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe:
```
Issue Number: #1191
using the key `examples`, it allows you to pass an object with multiple values, see example dto:
```
export class sampleDto {
@ApiProperty({
type: String,
description: 'desc...',
examples: {
value1: { value: 'foo1' },
value2: { value: 'foo2' },
},
})
value: string;
}
```
```
[ ] Yes
[x] No
```
This PR, improvement in schema object interface, using the key `examples`, it allows you to pass an object with multiple values, see screenshot and see issue …
> chore(): improvement in schema object interface

- lib/interfaces/open-api-spec.interface.ts
- lib/services/swagger-types-mapper.ts
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe:
```
Issue Number: #1170
Added options pattern properties
```
[ ] Yes
[x] No
```
This PR, added options pattern properties
> feat(): added options pattern properties

- e2e/api-spec.json
- e2e/src/cats/cats.controller.ts
- e2e/validate-schema.e2e-spec.ts
- lib/decorators/api-extension.decorator.ts
```
[x] Bugfix
[ ] Feature
```
Issue Number: #1130 
Correctly handle array in ApiExtension
```
[ ] Yes
[x] No
```
> fix(api-extension): Handle correct array value

- lib/services/schema-object-factory.ts
- package-lock.json
- package.json
- test/services/fixtures/create-user.dto.ts
- test/services/schema-object-factory.spec.ts
```
[x] Bugfix
[ ] Feature
```
Issue Number: #1178
Fixes the bug.
```
[ ] Yes
[x] No
```
The set of possible fields that should be moved from the outer type to the inner type in this case could be expanded. I picked a set of fields that match my own use cases, but these might not be exhaustive!
> Array format placement

- lib/services/mimetype-content-wrapper.ts
loop less times to reduce processing time and make code cleaner
```
[ ] Bugfix
[ ] Feature
```
There is use of loops 2 times in the file ```lib/services/mimetype-content-wrapper.ts``` which might be reduced and written more cleanly
Use single loop to get the result, more efficient, faster processing, fewer and cleaner code
```
[ ] Yes
[x] No
```
> refactor(@nestjs/swagger) reduce loop in MimetypeContentWrapper

- lib/decorators/api-param.decorator.ts
- test/explorer/swagger-explorer.spec.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> feat: add format in ApiParam decorator

- lib/decorators/api-extra-models.decorator.ts
- lib/swagger-explorer.ts
- test/explorer/swagger-explorer.spec.ts
```
[x] The commit message follows our guidelines: https://github.com/nestjs/nest/blob/master/CONTRIBUTING.md
[x] Tests for the changes have been added (for bug fixes / features)
[ ] Docs have been added / updated (for bug fixes / features)
```
```
[ ] Bugfix
[x] Feature
```
Issue Number: #1366
```
[ ] Yes
[x] No
```
> feat(@nest/swagger): multiple @ApiExtraModels on same method/controller

- lib/services/swagger-types-mapper.ts
```
[x] Bugfix
[ ] Feature
```
Issue Number: https://github.com/nestjs/swagger/issues/1295
`minLength` and `maxLength` are in `"schema"` block in generated JSON.
```
[ ] Yes
[x] No
```
> fix(): add string length options to schemaOptionsKeys

- lib/interfaces/swagger-custom-options.interface.ts
```
[x] Bugfix
[ ] Feature
```
Typescript gives an error.
Typescript don't gives an error.
```
[ ] Yes
[x] No
```
> fix: add `persistAuthorization` property to uiConfig

- lib/decorators/api-extra-models.decorator.ts
- lib/decorators/api-property.decorator.ts
- lib/explorers/api-exclude-controller.explorer.ts
- lib/interfaces/swagger-custom-options.interface.ts
- lib/swagger-module.ts
- lib/utils/get-global-prefix.ts
The code seems to have slightly deviated from the standards (`npm run format`). Didn't want to combine these irrelevant changes with my other pull request, so opening this one instead.
Ran `npm run format` to fix up any inconsistencies.
> style: format code

- lib/interfaces/swagger-custom-options.interface.ts
Typescript shows an error that `tagsSorter` and `operationsSorter` are missing from the `FastifySwaggerCustomOptions` interface. They are in fact supported but missing.
Issue Number: Similar to issue https://github.com/nestjs/swagger/issues/1589
More info on `tagsSorter` and `operationsSorter` here - https://github.com/swagger-api/swagger-ui/blob/master/docs/usage/configuration.md
Allow specifying `tagsSorter` or `operationsSorter` in `uiConfig`
> Add tagsSorter and operationsSorter to FastifySwaggerCustomOptions

- lib/plugin/utils/ast-utils.ts
- lib/plugin/utils/plugin-utils.ts
- lib/services/schema-object-factory.ts
- test/plugin/fixtures/create-cat-alt.dto.ts
- test/services/fixtures/create-user.dto.ts
- test/services/schema-object-factory.spec.ts
Issue Number: #1768 
The CLI plugin will now automatically annotate bigint properties and will not throw a `Cicular dependency error` when stumbling upon a bigint property.
> feat: add plugin support for bigint

- e2e/api-spec.json
- e2e/src/cats/cats.controller.ts
- e2e/validate-schema.e2e-spec.ts
- lib/decorators/helpers.ts
```
[x] Bugfix
[ ] Feature
```
Issue Number: #1524
```
[ ] Yes
[x] No
```
> fix(api-extension): support for multiple api-extension

- plugin.js
Same as https://github.com/nestjs/graphql/pull/2072
> feat(plugin): add export for cli plugin for ts-patch/ttypescript

- e2e/express.e2e-spec.ts
- e2e/fastify.e2e-spec.ts
- lib/swagger-module.ts
- package-lock.json
- package.json
Issue Number: [1965](https://github.com/nestjs/swagger/issues/1964)
> fix(): content type issue, added test cases

- e2e/manual-e2e.ts
- lib/swagger-module.ts
Issue Number: [9913](https://github.com/nestjs/nest/issues/9913)
> fix():  breaking issue caused by passing 'ignoreTrailingSlash: true' 

- lib/swagger-ui/swagger-ui.ts
Issue Number: [1970](https://github.com/nestjs/swagger/issues/1970)
> fix(): added default value for custom swagger options

- e2e/manual-e2e.ts
- lib/swagger-module.ts
Issue Number: [1976](https://github.com/nestjs/swagger/issues/1976)
> fix(): fixed issues caused by accessing nestjs-swagger behind reverse proxy

- .circleci/config.yml
- lib/plugin/utils/plugin-utils.ts
- lib/plugin/visitors/abstract.visitor.ts
- lib/plugin/visitors/controller-class.visitor.ts
- lib/plugin/visitors/model-class.visitor.ts
- package-lock.json
- package.json
- test/plugin/fixtures/create-cat-alt.dto.ts
- test/plugin/fixtures/create-cat-alt2.dto.ts
- test/plugin/fixtures/create-cat.dto.ts
- test/plugin/fixtures/nullable.dto.ts
- test/plugin/fixtures/string-literal.dto.ts
- test/plugin/model-class-visitor.spec.ts
> chore(): support typescript v4.8

- lib/swagger-ui/swagger-ui.ts
code:
```js
const start = Date.now();
const config = new DocumentBuilder().build();
const document = SwaggerModule.createDocument(app, config);
SwaggerModule.setup('api', app, document);
console.log(`Swagger loaded in ${Date.now() - start}ms`);
```
before: `Swagger loaded in 101ms`
after: `Swagger loaded in 26ms`
see: https://github.com/swagger-api/swagger-ui/issues/4502
> Optimize swagger-ui-dist loading performance

- lib/swagger-explorer.ts
- test/explorer/swagger-explorer.spec.ts
Closes #1946
Issue Number: #1946
> fix(): missing requestBody

- lib/decorators/api-response.decorator.ts
> fix: ApiResponseSchemaHost.status range support

- lib/interfaces/open-api-spec.interface.ts
> feat(@nestjs/swagger): Support for custom OAuth2 token name with `x-tokenName` parameter in security scheme

- lib/swagger-module.ts
I created a module for [Swagger Koa](https://github.com/SocketSomeone/nestjs-swagger-koa), but for it to work correctly, I want the methods of the class to be protected.
Issue Number: https://github.com/seidelmartin/nest-koa-adapter/issues/23
Pull Requst Number: https://github.com/nestjs/swagger/pull/2351
Private methods of Swagger Module now is protected
> feat: make methods of swagger module protected

- e2e/api-spec.json
- e2e/src/cats/dto/pagination-query.dto.ts
- lib/services/swagger-types-mapper.ts
- test/plugin/fixtures/project/cats/dto/pagination-query.dto.ts
- test/plugin/fixtures/serialized-meta.fixture.ts
Issue Number: https://github.com/nestjs/swagger/issues/3078
These fields will be supported properly for parameters, referencing the oneOf/anyOf constraints inside the schema instead of directly in the type for parameters.
> feat: Add schema support for more option keys

- e2e/api-spec.json
- lib/services/schema-object-factory.ts
- lib/services/swagger-types-mapper.ts
> fix: spread query parameters if feasible 

- e2e/api-spec.json
- e2e/src/cats/cats.controller.ts
- lib/services/response-object-mapper.ts
> fix: omit schema field in response object 

- lib/plugin/merge-options.ts
- lib/plugin/visitors/controller-class.visitor.ts
> feat: allow skipping auto http code annotation

- lib/plugin/utils/plugin-utils.ts
- lib/plugin/visitors/controller-class.visitor.ts
- lib/plugin/visitors/model-class.visitor.ts
> Revert "fix(plugin): resolve compiler option paths relative to base"

- e2e/api-spec.json
- e2e/src/cats/classes/cat.class.ts
- lib/interfaces/schema-object-metadata.interface.ts
> fix: expose self required attribute for objects

- lib/decorators/api-property.decorator.ts
- test/services/schema-object-factory.spec.ts
Issue Number: #3229 
`@ApiProperty({enum: undefined})` doesn't modify type
> fix: missing ApiProperty enum undefined handling

- lib/plugin/utils/plugin-utils.ts
- test/plugin/fixtures/parameter-property.dto.ts
- test/plugin/fixtures/serialized-meta.fixture.ts
> Revert "feat: make generated require() ESM compatible"

- lib/services/schema-object-factory.ts
- test/services/schema-object-factory.spec.ts
Issue Number: [#3368](https://github.com/nestjs/swagger/issues/3368)
Generated schemas correctly reference the custom schema names:
```
"#/components/schemas/MenuNode"
```
> fix: recursive schema reference handling #3368
